# ============================
# Project information
# ============================
site_name: 'Ma Kaijing'
site_description: 'Personal Website of Ma Kaijing'

# Repository ä¿¡æ¯ï¼ˆå¦‚æœä½ ä¸éœ€è¦å¯ä»¥åˆ é™¤ï¼‰
repo_name: 'ma-kaijing-profile'
repo_url: 'https://github.com/mkj3085003/ma-kaijing-profile'

# Copyright
copyright: 'Kaijing Ma'

# ============================
# Theme Configuration
# ============================
# Configuration
theme:
  name: material

plugins:
  - search
  - mkdocstrings


# ============================
# Navigation
# ============================
nav:
  - "ğŸŒ¸ Hello!": index.md
  - "ğŸŒ¼ My Little Projects": projects.md
  - "ğŸ¤– Robo Adventures": robotics.md
  - "ğŸ”­ Research Journey": research.md


